// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Planet x Cannabis",
  domain: "theplanetx.ca",
  city: "North York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-north-york",
  address: "3005 Islington Ave unit 1, North York, ON M9L 2K9",
  streetAddress: "3005 Islington Ave unit 1",
  postalCode: "M9L 2K9",
  phone: "(226) 545-3005",
  phoneIntl: "+12265453005",
  neighborhood: "North York",
  nearbyAreas: ["Islington Avenue", "Steeles Avenue West", "North York", "Humber Summit", "York University", "Humber College", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=3005+Islington+Ave+unit+1,+North+York,+ON+M9L+2K9",
  mapEmbedUrl: "https://maps.google.com/maps?q=Planet%20x%20Cannabis%203005%20Islington%20Ave%20unit%201%2C%20North%20York%2C%20ON%20M9L%202K9&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7554",
  longitude: "-79.5645",
  hours: ["Open 24 Hours"],
  seoTitle: "Planet x Cannabis | Weed Dispensary in North York",
  metaDescription: "Planet x Cannabis is a local weed dispensary in North York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Islington Avenue", "Steeles Avenue West", "North York"],
  introVariant: "If you are searching for a reliable weed dispensary in North York, Planet x Cannabis at 3005 Islington Ave unit 1 is your go-to destination. We serve adults 19+ with a vast selection of weed products including cannabis flower, pre-rolls, edibles, THC vapes, shatter, and CBD oils. Serving customers near North York and surrounding communities like Steeles Avenue West, our cannabis store and weed shop is focused on quality and convenience.",
  neighborhoodDescription: "Located in the vibrant North York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Free plaza parking is available on-site",
  transitNote: "Accessible via TTC bus routes along Islington Avenue and Steeles Avenue West.",
  sectionTitle: "Serving Customers Near North York and Nearby Communities"
};
