export type WeedDiscoveryLink = { label: string; description: string; href: string };
export type WeedFaq = { question: string; answer: string };

export const weedOwner = {
  storeName: "The Planet X Cannabis",
  domain: "www.theplanetx.ca",
  ownerPath: "/weed-dispensary-north-york/",
  city: "North York",
  streetAddress: "3005 Islington Ave Unit 1",
  postalCode: "M9L 2K9",
  phoneDisplay: "+1 (289) 217-2773",
  phoneIntl: "+12892172773",
  hoursLabel: "Open 24 Hours · 7 Days a Week",
  openingHours: "Mo-Su 00:00-23:59",
  seoTitle: "Weed Dispensary in North York | The Planet X Cannabis",
  metaDescription: "The Planet X Cannabis is open 24 hours at 3005 Islington Ave Unit 1 in North York. Adults 19+ can explore cannabis and flower shopping guides.",
  h1: "The Planet X Cannabis — Weed Dispensary in North York",
  introTitle: "Weed and Cannabis at The Planet X",
  intro: [
    "The Planet X Cannabis is located at 3005 Islington Ave Unit 1 in North York — a 24-hour walk-in on the Islington Avenue and Steeles Avenue West edge of Humber Summit.",
    "Adults 19+ can use flower information and cannabis-format guides to decide where they want to start. For a particular product, call +1 (289) 217-2773 before making a special trip. Transit, parking, and unit 1 notes live on the supporting /visit page. Overnight / open-now intent lives on the 24-hour Islington & Steeles page. NAP, hours, and the map stay on the homepage. This North York page stays the corridor landing — not a Toronto city page.",
  ],
  findTitle: "Find Your Weed at Planet X",
  discoveryLinks: [
    { label: "Exotic Flower", description: "Top-shelf Exotic collection at unit 1.", href: "/exotic-weed" },
    { label: "Premium Flower", description: "Humber Summit Premium lane — $7–$10/g.", href: "/premium-weed" },
    { label: "AAA+ Flower", description: "Mid-shelf AAA+ at 3005 Islington Ave unit 1.", href: "/aaa-weed" },
    { label: "AA Flower", description: "Steeles West daily-driver grams at $4/g.", href: "/aa-weed" },
    { label: "Budget Flower", description: "Cheapest published lane from $3/g.", href: "/budget-weed" },
    { label: "24-Hour Islington & Steeles", description: "Overnight / open-now walk-in at unit 1.", href: "/24-hour-islington-steeles-dispensary" },
    { label: "Cannabis Delivery Islington & Steeles", description: "Corridor delivery from unit 1 — not city-wide Toronto.", href: "/cannabis-delivery-islington-steeles" },
  ] satisfies WeedDiscoveryLink[],
  guides: [
    { label: "Homepage Visit Hub", description: "NAP, hours, and the map stay on the homepage.", href: "/" },
    { label: "How to Find Unit 1", description: "Plaza entrance, TTC on Islington and Steeles, parking.", href: "/visit" },
    { label: "24-Hour Islington & Steeles", description: "Overnight and open-now intent for this door.", href: "/24-hour-islington-steeles-dispensary" },
    { label: "Cannabis Delivery Islington & Steeles", description: "Neighbourhood delivery from unit 1. Confirm the street.", href: "/cannabis-delivery-islington-steeles" },
    { label: "Native Cigarettes", description: "Adult 19+ cigarette category for this corridor.", href: "/info/native-cigarettes-islington-steeles" },
    { label: "Nicotine Vape Islington & Steeles", description: "Neighbourhood nicotine guide — live category /items/vapes.", href: "/info/nicotine-vapes-islington-steeles" },
    { label: "Islington North York Visit Guide", description: "Store-specific visit information.", href: "/resources/islington-north-york-weed-visit-guide" },
    { label: "Flower Guide", description: "Learn more about cannabis flower.", href: "/resources/weed-flower-guide" },
    { label: "Value Guide", description: "Explore value-oriented shopping.", href: "/resources/weed-value-guide" },
  ] satisfies WeedDiscoveryLink[],
  faq: [
    { question: "Where is The Planet X Cannabis?", answer: "The Planet X Cannabis is located at 3005 Islington Ave Unit 1, North York, ON M9L 2K9, on the Islington and Steeles edge of Humber Summit." },
    { question: "Is The Planet X Cannabis open 24 hours?", answer: "Yes. It is open 24 hours a day, seven days a week at 3005 Islington Ave unit 1. Overnight / open-now copy lives on the 24-hour Islington & Steeles page. This North York page stays the weed corridor owner." },
    { question: "How do I find unit 1?", answer: "Use the plaza entrance marked unit 1 on the Islington frontage. The supporting /visit page covers parking and TTC along Islington Avenue and Steeles Avenue West. NAP stays on the homepage." },
    { question: "What is the difference between weed and cannabis?", answer: "Weed is casual everyday terminology. Cannabis is the broader term." },
    { question: "What is the difference between bud and flower?", answer: "Bud is an informal word commonly used for cannabis flower." },
    { question: "Can I explore flower information before visiting?", answer: "Yes. The Flower Guide and verified Exotic and Premium sections provide starting points." },
    { question: "Does “Planet X weed” refer to one specific product?", answer: "The Planet X Cannabis is the store name. A phrase using the store name does not by itself confirm a specific strain or product. Call +1 (289) 217-2773 if you are looking for something particular." },
    { question: "How can I ask about a specific product?", answer: "Call +1 (289) 217-2773." },
    { question: "Do I need to be 19+?", answer: "Yes." },
  ] satisfies WeedFaq[],
  home: {
    title: "Weed in North York at Planet X",
    text: "The Planet X Cannabis is open 24 hours at 3005 Islington Ave Unit 1 in Humber Summit, North York — Islington & Steeles walk-in. Adults 19+ can explore this North York weed corridor, use /visit for unit 1, transit, and parking, and use the 24-hour Islington & Steeles page for overnight intent. NAP stays on the homepage.",
    primaryLabel: "Explore Weed in North York",
    secondaryLabel: "Explore the Flower Guide",
    secondaryHref: "/resources/weed-flower-guide",
  },
};
